source 'https://github.com/CocoaPods/Specs.git'

# Required for Swift apps
platform :ios, '8.0'
use_frameworks!

# Pods for LearnYouKanji:
# The target name is most likely the name of your project.
target 'LearnYouKanji' do

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge', # bridge ?
    # 'CxxBridge', # bridge ?
    # 'RCTAnimation', # Error with this one
    # 'RCTDeviceEventEmitter', # deprecated ?
    'RCTPushNotification',
    'RCTImage',
    'RCTLinkingIOS', # bridge
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

end
